const LOGIN_TODO_REQUEST = "LOGIN_TODO_REQUEST";
const LOGIN_TODO_SUCCESS = "LOGIN_TODO_SUCCESS";
const LOGIN_TODO_FAILURE = "LOGIN_TODO_FAILURE";
const LOGIN_TODO_LOGOUT = "LOGIN_TODO_LOGOUT";

export {
  LOGIN_TODO_FAILURE,
  LOGIN_TODO_REQUEST,
  LOGIN_TODO_LOGOUT,
  LOGIN_TODO_SUCCESS
};
