const GET_CLOTH_REQUEST = "GET_CLOTH_REQUEST";
const GET_CLOTH_SUCCESS = "GET_CLOTH_SUCCESS";
const GET_CLOTH_FAILURE = "GET_CLOTH_FAILURE";
const GET_CART_REQUEST = "GET_CART_REQUEST";
const GET_CART_SUCCESS = "GET_CART_SUCCESS";
const GET_CART_FAILURE = "GET_CART_FAILURE";
const ADD_CLOTH_REQUEST = "ADD_CLOTH_REQUEST";
const ADD_CLOTH_SUCCESS = "ADD_CLOTH_SUCCESS";
const ADD_CLOTH_FAILURE = "ADD_CLOTH_FAILURE";
const DELETE_CLOTH = "DELETE_CLOTH";
const UPDATE_CLOTH = "UPDATE_CLOTH";

export {
  GET_CLOTH_SUCCESS,
  GET_CLOTH_FAILURE,
  GET_CLOTH_REQUEST,
  GET_CART_SUCCESS,
  GET_CART_FAILURE,
  GET_CART_REQUEST,
  ADD_CLOTH_REQUEST,
  ADD_CLOTH_SUCCESS,
  ADD_CLOTH_FAILURE,
  DELETE_CLOTH,
  UPDATE_CLOTH
};
